struct PLACEHOLDER_1<PLACEHOLDER_2>(PLACEHOLDER_2);
struct PLACEHOLDER_3<PLACEHOLDER_2, PLACEHOLDER_4> {
    PLACEHOLDER_5: PLACEHOLDER_2,
    PLACEHOLDER_6: PLACEHOLDER_4,
}
impl<PLACEHOLDER_2, PLACEHOLDER_4> PLACEHOLDER_3<PLACEHOLDER_2, PLACEHOLDER_4> {
    fn PLACEHOLDER_7() {
        let PLACEHOLDER_8 = 3;
    }
}
